(() => {
  const cfg=window.DREAMCATCHER_SUPABASE||{}, dialog=document.querySelector("#accountDialog");
  const configured=Boolean(cfg.url&&cfg.publishableKey&&window.supabase?.createClient);
  let client=null,user=null,syncTimer=null,syncing=false,lastUser=null,profile={nickname:""},wormholes=[],textEntryAction=null,activeWormhole=null,realtimeChannel=null,currentDreamId=null;
  const show=(id,on)=>document.querySelector(id)?.classList.toggle("hidden",!on);
  const msg=(t,b=false)=>{const e=document.querySelector("#authMessage");if(e){e.textContent=t||"";e.classList.toggle("error",b)}};
  const state=()=>window.dreamcatcherState;
  const toRow=d=>({id:d.id,user_id:user.id,dream_date:d.date,title:d.title||"",content:d.content||"",category:d.category||null,moods:Array.isArray(d.mood)?d.mood:(d.mood?[d.mood]:[]),body_sensations:d.body||[],life_context:d.context||"",analysis:d.analysis||null,analysis_generated_at:d.analysisGeneratedAt||null,created_at:d.createdAt?new Date(d.createdAt).toISOString():new Date().toISOString(),updated_at:d.updatedAt?new Date(d.updatedAt).toISOString():new Date().toISOString()});
  const fromRow=r=>({id:r.id,date:r.dream_date,title:r.title||"",content:r.content||"",category:r.category||"",mood:r.moods||[],body:r.body_sensations||[],context:r.life_context||"",analysis:r.analysis||"",analysisGeneratedAt:r.analysis_generated_at||null,createdAt:new Date(r.created_at).getTime(),updatedAt:new Date(r.updated_at).getTime()});
  async function pushAll(){
    if(!user||syncing||!state())return; syncing=true;
    try{
      const local=state().getDreams(), rows=local.map(toRow);
      if(rows.length){const {error}=await client.from("dreams").upsert(rows,{onConflict:"id"});if(error)throw error}
      const c=state().getCustom(), opts=[];
      for(const type of ["category","mood","body"])for(const value of (c[type]||[]))opts.push({user_id:user.id,option_type:type,value});
      if(opts.length){const {error}=await client.from("custom_options").upsert(opts,{onConflict:"user_id,option_type,value",ignoreDuplicates:true});if(error)throw error}
      await pullAll();
    }catch(e){console.error("Dreamcatcher sync:",e);msg("云同步失败："+e.message,true)}
    finally{syncing=false}
  }
  async function pullAll(){
    if(!user||!state())return;
    const [{data:remote,error:e1},{data:opts,error:e2}]=await Promise.all([
      client.from("dreams").select("*").order("dream_date",{ascending:false}),
      client.from("custom_options").select("option_type,value")
    ]);
    if(e1||e2)throw(e1||e2);
    const local=state().getDreams(), map=new Map(local.map(d=>[d.id,d]));
    for(const r of remote||[]){const d=fromRow(r),old=map.get(d.id);if(!old||d.updatedAt>=old.updatedAt)map.set(d.id,d)}
    state().setDreams([...map.values()]);
    const c={...state().getCustom(),category:[...(state().getCustom().category||[])],mood:[...(state().getCustom().mood||[])],body:[...(state().getCustom().body||[])]};
    for(const o of opts||[])if(c[o.option_type]&&!c[o.option_type].includes(o.value))c[o.option_type].push(o.value);
    state().setCustom(c);
  }
  async function loadProfile(){if(!user)return;const {data,error}=await client.rpc("get_my_profile");if(!error)profile={nickname:data?.[0]?.nickname||""}}
  async function loadWormholes(){if(!user)return[];const {data,error}=await client.from("wormholes").select("*").order("created_at",{ascending:false});if(error)throw error;wormholes=data||[];return wormholes}
  async function partner(w){const {data,error}=await client.rpc("get_wormhole_partner",{target_wormhole:w.id});if(error)throw error;return data?.[0]||{}}
  async function loadSharedTimeline(){if(!user||!state())return;try{await loadWormholes();const active=wormholes.find(w=>w.status==="accepted");activeWormhole=active||null;if(!active){state().setSharedDreams([]);state().setUnreadDreams?.({});return}const p=await partner(active),{data,error}=await client.rpc("get_shared_wormhole_dreams",{target_wormhole:active.id});if(error)throw error;state().setSharedDreams((data||[]).map(r=>({...fromRow(r),remote:true,ownerName:p.nickname||"TA",wormholeId:active.id})));await loadUnread(active.id)}catch(e){console.error("Shared timeline:",e)}}

  async function loadUnread(wid){const {data,error}=await client.rpc("get_wormhole_unread_dreams",{target_wormhole:wid});if(error)return console.error("Unread:",error);state().setUnreadDreams?.(Object.fromEntries((data||[]).filter(x=>Number(x.unread_count)>0).map(x=>[x.dream_id,Number(x.unread_count)])))}
  const fmtTime=s=>{const d=new Date(s),now=new Date(),same=d.toDateString()===now.toDateString();return (same?"今天":d.toLocaleDateString("zh-CN",{month:"numeric",day:"numeric"}))+" "+d.toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})};
  async function loadComments(dreamId){if(!activeWormhole)return;currentDreamId=dreamId;const {data,error}=await client.rpc("get_wormhole_comments",{target_wormhole:activeWormhole.id,target_dream:dreamId});const box=document.querySelector("#dreamComments");if(error){if(box)box.innerHTML='<p class="muted">评论加载失败</p>';return}if(box){const roots=(data||[]).filter(x=>!x.parent_id),children=id=>(data||[]).filter(x=>x.parent_id===id);const item=(x,reply=false)=>'<div class="comment-item '+(reply?"comment-reply":"")+'"><div class="comment-meta"><b>'+safe(x.author_name)+'</b><small>'+fmtTime(x.created_at)+'</small></div><p>'+safe(x.body)+'</p><div class="comment-actions"><button data-reply-comment="'+x.id+'" data-dream-id="'+dreamId+'" data-author="'+safe(x.author_name)+'">回复</button><button class="'+(x.liked_by_me?"liked":"")+'" data-like-comment="'+x.id+'" data-dream-id="'+dreamId+'">♥ '+Number(x.like_count||0)+'</button></div>'+children(x.id).map(y=>item(y,true)).join("")+'</div>';box.innerHTML=roots.length?roots.map(x=>item(x)).join(""):'<p class="muted">还没有评论，留下第一句话吧。</p>'}await client.rpc("mark_wormhole_dream_read",{target_wormhole:activeWormhole.id,target_dream:dreamId});await loadUnread(activeWormhole.id)}
  window.addEventListener("dreamcatcher:opendream",async e=>{if(!user||!activeWormhole)return;const id=e.detail?.dreamId;const shared=state().getSharedDreams().some(d=>d.id===id);let mine=false;if(!shared){const {data}=await client.from("wormhole_dreams").select("dream_id").eq("wormhole_id",activeWormhole.id).eq("dream_id",id).eq("owner_id",user.id).maybeSingle();mine=!!data}if(shared||mine)await loadComments(id)});
  window.addEventListener("dreamcatcher:replycomment",e=>{if(!user||!activeWormhole)return;const q=e.detail;openEntry({title:"回复 "+(q.author||""),hint:"回复会显示在这条评论下面。",placeholder:"写下回复…",onSubmit:async body=>{const {error}=await client.rpc("add_wormhole_comment",{target_wormhole:activeWormhole.id,target_dream:q.dreamId,comment_body:body,reply_to:q.commentId});if(error){alert("回复失败："+error.message);return false}await loadComments(q.dreamId);return true}})});
  window.addEventListener("dreamcatcher:likecomment",async e=>{const q=e.detail;if(!user)return;const {error}=await client.rpc("toggle_wormhole_comment_like",{target_comment:q.commentId});if(error)return alert("点赞失败："+error.message);await loadComments(q.dreamId)});
  function startRealtime(){if(!client||!user)return;if(realtimeChannel)client.removeChannel(realtimeChannel);realtimeChannel=client.channel("dreamcatcher-wormhole-"+user.id).on("postgres_changes",{event:"*",schema:"public",table:"wormhole_comments"},async payload=>{const row=payload.new?.id?payload.new:payload.old;if(!activeWormhole||row?.wormhole_id!==activeWormhole.id)return;if(currentDreamId===row.dream_id&&document.querySelector("#viewDreamDialog")?.open)await loadComments(row.dream_id);else await loadUnread(activeWormhole.id)}).on("postgres_changes",{event:"*",schema:"public",table:"wormhole_comment_likes"},async()=>{if(!activeWormhole)return;if(currentDreamId&&document.querySelector("#viewDreamDialog")?.open)await loadComments(currentDreamId);else await loadUnread(activeWormhole.id)}).subscribe()}
  async function syncNow(){if(user){await pushAll();await loadSharedTimeline();msg("已同步到云端 ✓")}}
  async function refresh(){
    if(!configured)return;
    const {data}=await client.auth.getSession(); user=data.session?.user||null;
    show("#authForms",!user);show("#signedInPanel",!!user);show("#authNotConfigured",false);
    if(user){document.querySelector("#signedInEmail").textContent=user.email||"已登录";if(lastUser!==user.id){lastUser=user.id;await syncNow();await loadProfile();await loadWormholes();startRealtime()}else await loadSharedTimeline()}
    else{lastUser=null;if(realtimeChannel){client.removeChannel(realtimeChannel);realtimeChannel=null}}
  }
  window.addEventListener("dreamcatcher:analyzedream",async e=>{if(!user)return dialog.showModal();const id=e.detail?.dreamId,d=state().getDreams().find(x=>x.id===id);if(!d)return;const btn=document.querySelector('[data-ai-dream="'+id+'"]');if(btn){btn.disabled=true;btn.textContent="正在解梦…"}try{const {data,error}=await client.functions.invoke("super-action",{body:{dream:{title:d.title,content:d.content,category:d.category,mood:d.mood,body:d.body,context:d.context}}});if(error)throw error;if(!data?.analysis)throw new Error(data?.error||"没有收到分析结果");const next={...d,analysis:data.analysis,analysisGeneratedAt:data.generatedAt||new Date().toISOString(),updatedAt:Date.now()};state().setDreams(state().getDreams().map(x=>x.id===id?next:x));await pushAll();document.querySelector("#viewDreamDialog")?.close();setTimeout(()=>{window.dispatchEvent(new CustomEvent("dreamcatcher:reopenown",{detail:{dreamId:id}}))},30)}catch(err){console.error("AI dream analysis:",err);if(btn){btn.disabled=false;btn.textContent=d.analysis?"重新解梦":"开始解梦"}alert("AI 解梦失败："+(err?.message||"请稍后再试"))}});
  window.addEventListener("dreamcatcher:openaccount",()=>dialog.showModal());
  const noticeDialog=document.querySelector("#noticeDialog");function notice(title,message){document.querySelector("#noticeTitle").textContent=title;document.querySelector("#noticeMessage").textContent=message;noticeDialog.showModal()}document.querySelector("#noticeOk").onclick=()=>noticeDialog.close();
  let confirmAction=null;const confirmDialog=document.querySelector("#confirmDialog"),confirmOk=document.querySelector("#confirmOk");function openConfirm({title,message,confirmText="确定",tone="",action,payload}){document.querySelector("#confirmTitle").textContent=title;document.querySelector("#confirmMessage").textContent=message;confirmOk.textContent=confirmText;confirmOk.classList.toggle("confirm-danger",tone==="danger");confirmAction={action,payload};confirmDialog.showModal()}window.addEventListener("dreamcatcher:confirm",e=>openConfirm(e.detail||{}));window.addEventListener("dreamcatcher:signout",()=>{if(!user)return dialog.showModal();openConfirm({title:"退出登录？",message:"你的云端梦境会保留，下次登录后可以继续同步。",confirmText:"退出登录",action:"signout"})});document.querySelector("#confirmCancel").onclick=()=>{confirmAction=null;confirmDialog.close()};confirmOk.onclick=async()=>{const q=confirmAction;confirmOk.disabled=true;try{if(q?.action==="signout"){await client.auth.signOut();msg("")}else if(q?.action==="delete-custom"){window.dispatchEvent(new CustomEvent("dreamcatcher:deletecustomconfirmed",{detail:q.payload}))}else if(q?.action==="delete-dream"){window.dispatchEvent(new CustomEvent("dreamcatcher:deletedreamconfirmed",{detail:q.payload}))}else if(q?.action==="disconnect-wormhole"){window.dispatchEvent(new CustomEvent("dreamcatcher:disconnectwormholeconfirmed",{detail:q.payload}))}confirmAction=null;confirmDialog.close()}finally{confirmOk.disabled=false}};
  const entryDialog=document.querySelector("#textEntryDialog"),entryForm=document.querySelector("#textEntryForm");
  function openEntry({title,hint="",value="",placeholder="",maxLength=1000,onSubmit}){textEntryTitle.textContent=title;textEntryHint.textContent=hint;textEntryValue.value=value;textEntryValue.placeholder=placeholder;textEntryValue.maxLength=maxLength;textEntryAction=onSubmit;entryDialog.showModal();setTimeout(()=>textEntryValue.focus(),50)}
  closeTextEntryBtn.onclick=()=>entryDialog.close();
  entryForm.onsubmit=async e=>{e.preventDefault();const value=textEntryValue.value.trim();if(!value)return;const btn=textEntrySubmit;btn.disabled=true;try{if(await textEntryAction?.(value)!==false)entryDialog.close()}finally{btn.disabled=false}};
  window.addEventListener("dreamcatcher:comment",e=>{if(!user)return dialog.showModal();const d=state().getSharedDreams().find(x=>x.id===e.detail?.dreamId);if(!d)return;openEntry({title:"写下评论",hint:"给 "+(d.ownerName||"TA")+" 的梦留下一句话",placeholder:"写下你的想法…",onSubmit:async body=>{const {error}=await client.rpc("add_wormhole_comment",{target_wormhole:d.wormholeId,target_dream:d.id,comment_body:body,reply_to:null});if(error){alert("评论发送失败："+error.message);return false}await loadComments(d.id);return true}})});
  window.addEventListener("dreamcatcher:textentry",e=>{const q=e.detail||{};if(q.kind!=="custom")return;openEntry({title:q.title,hint:q.hint,maxLength:q.maxLength||18,onSubmit:async value=>{window.dispatchEvent(new CustomEvent("dreamcatcher:addcustom",{detail:{optionType:q.optionType,value}}));return true}})});
  window.addEventListener("dreamcatcher:deletecustom",async e=>{if(!user)return;const q=e.detail||{};const {error}=await client.from("custom_options").delete().eq("user_id",user.id).eq("option_type",q.optionType).eq("value",q.value);if(error){console.error("Delete custom option:",error);alert("标签云端删除失败："+error.message)}});
  window.addEventListener("dreamcatcher:disconnectwormholeconfirmed",async e=>{const id=e.detail?.wormholeId;if(!id||!user)return;const {error}=await client.from("wormholes").delete().eq("id",id);if(error){console.error("Disconnect wormhole:",error);return alert("解除虫洞失败："+error.message)}activeWormhole=null;sharedDreams=[];window.dispatchEvent(new CustomEvent("dreamcatcher:sharedloaded",{detail:{dreams:[]}}));renderWormhole()});
  window.addEventListener("dreamcatcher:deletedream",async e=>{if(!user)return;const id=e.detail?.dreamId;if(!id)return;try{if(activeWormhole)await client.from("wormhole_dreams").delete().eq("dream_id",id).eq("owner_id",user.id);const {error}=await client.from("dreams").delete().eq("id",id).eq("user_id",user.id);if(error)throw error;await loadSharedTimeline()}catch(err){console.error("Delete dream:",err);alert("云端删除失败："+err.message)}});
  window.addEventListener("dreamcatcher:profile",async()=>{if(user)await loadProfile();const el=document.querySelector("#profileStatus"),name=document.querySelector("#profileNickname"),edit=document.querySelector("[data-nickname]"),out=document.querySelector("[data-signout-profile]");if(user){if(el)el.textContent=user.email||"已登录";if(name)name.textContent=profile.nickname||"未设置昵称";if(edit)edit.hidden=false;if(out)out.hidden=false}else{if(el)el.textContent="注册或登录后使用云同步与虫洞";if(name)name.textContent="注册 Dreamcatcher";if(edit)edit.hidden=true;if(out)out.hidden=true;setTimeout(()=>window.dispatchEvent(new CustomEvent("dreamcatcher:openaccount")),0)}});
  window.addEventListener("dreamcatcher:editnickname",()=>{if(!user)return dialog.showModal();openEntry({title:"编辑昵称",hint:"昵称会显示给与你建立虫洞的人。",value:profile.nickname,maxLength:30,onSubmit:async clean=>{const {error}=await client.rpc("set_my_nickname",{new_nickname:clean});if(error){alert("保存失败："+error.message);return false}profile.nickname=clean;const el=document.querySelector("#profileNickname");if(el)el.textContent=clean;return true}})});
  window.addEventListener("dreamcatcher:prepare-share",async e=>{const row=document.querySelector("#shareWormholeRow"),toggle=document.querySelector("#shareWormhole");if(!user){row.classList.add("hidden");return}await loadWormholes();const active=wormholes.find(w=>w.status==="accepted");if(!active){row.classList.add("hidden");return}row.classList.remove("hidden");if(e.detail?.dreamId){const {data}=await client.from("wormhole_dreams").select("dream_id").eq("wormhole_id",active.id).eq("dream_id",e.detail.dreamId).eq("owner_id",user.id).maybeSingle();toggle.checked=!!data}});
  window.addEventListener("dreamcatcher:save-share",async e=>{if(!user)return;await loadWormholes();const active=wormholes.find(w=>w.status==="accepted");if(!active)return;const {dreamId,share}=e.detail||{};if(!dreamId)return;if(share){const {error}=await client.from("wormhole_dreams").upsert({wormhole_id:active.id,dream_id:dreamId,owner_id:user.id},{onConflict:"wormhole_id,dream_id"});if(error)console.error("Share dream:",error)}else await client.from("wormhole_dreams").delete().eq("wormhole_id",active.id).eq("dream_id",dreamId).eq("owner_id",user.id);await loadSharedTimeline()});
  window.addEventListener("dreamcatcher:openwormhole",async()=>{if(!user)return dialog.showModal();await renderWormhole();document.querySelector("#wormholeDialog").showModal()});
  document.querySelector("#closeWormholeBtn").onclick=()=>document.querySelector("#wormholeDialog").close();
  async function renderWormhole(){const box=document.querySelector("#wormholeContent");box.innerHTML='<p class="muted">正在连接虫洞…</p>';try{await loadWormholes();const active=wormholes.find(w=>w.status==="accepted"),incoming=wormholes.filter(w=>w.status==="pending"&&w.receiver_id===user.id),outgoing=wormholes.filter(w=>w.status==="pending"&&w.sender_id===user.id);if(active){activeWormhole=active;const p=await partner(active),bound=new Date(active.responded_at||active.created_at),days=Math.max(1,Math.floor((Date.now()-bound.getTime())/86400000)+1);box.innerHTML='<div class="connected wormhole-summary"><div class="wormhole-icon">✦</div><h3>与 '+safe(p.nickname||"未设置昵称")+' 的虫洞</h3><p class="muted">'+safe(p.email||"")+'</p><div class="bond-stats"><div><b>'+bound.toLocaleDateString("zh-CN")+'</b><small>绑定时间</small></div><div><b>'+days+'</b><small>绑定天数</small></div></div><button class="danger-btn" data-disconnect="'+active.id+'">解除虫洞</button></div>';bindWormhole(active.id);return}let incomingHtml="";for(const w of incoming){const p=await partner(w);incomingHtml+='<div class="invite-card"><b>'+safe(p.nickname||"Dreamcatcher 用户")+'</b><small>'+safe(p.email||"")+'</small><div><button class="primary-btn" data-accept="'+w.id+'">接受</button><button class="secondary-btn" data-decline="'+w.id+'">拒绝</button></div></div>'}box.innerHTML='<p>输入对方完整的 Dreamcatcher ID（邮箱）发送邀请。</p><label>Dreamcatcher ID<input id="wormholeEmail" type="email" placeholder="friend@example.com"></label><button id="sendWormholeInvite" class="primary-btn">发送虫洞邀请</button>'+(incomingHtml?'<h3 class="worm-section">收到的邀请</h3>'+incomingHtml:"")+(outgoing.length?'<p class="muted worm-section">你有 '+outgoing.length+' 个等待对方接受的邀请。</p>':"");bindWormhole()}catch(e){box.innerHTML='<p class="auth-message error">虫洞加载失败：'+safe(e.message)+'</p>'}}
  const safe=s=>String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  const remoteCard=d=>'<article class="shared-dream"><b>'+safe(d.title)+'</b><small>'+safe(d.dream_date)+'</small><p>'+safe(d.content)+'</p></article>';
  function bindWormhole(activeId){const send=document.querySelector("#sendWormholeInvite");if(send)send.onclick=async()=>{const email=document.querySelector("#wormholeEmail").value.trim();if(!email)return;send.disabled=true;const {error}=await client.rpc("send_wormhole_invite",{target_email:email});send.disabled=false;if(error)return alert("发送失败："+error.message);notice("邀请已发送","如果该邮箱对应 Dreamcatcher 账户，对方会在虫洞中看到邀请。");renderWormhole()};document.querySelectorAll("[data-accept]").forEach(b=>b.onclick=async()=>{const {error}=await client.rpc("accept_wormhole_invite",{target_wormhole:b.dataset.accept});if(error)return alert(error.message);renderWormhole()});document.querySelectorAll("[data-decline]").forEach(b=>b.onclick=async()=>{const {error}=await client.rpc("decline_wormhole_invite",{target_wormhole:b.dataset.decline});if(error)return alert(error.message);renderWormhole()});document.querySelectorAll("[data-share]").forEach(ch=>ch.onchange=async()=>{const row={wormhole_id:activeId,dream_id:ch.dataset.share,owner_id:user.id};const q=ch.checked?client.from("wormhole_dreams").insert(row):client.from("wormhole_dreams").delete().eq("wormhole_id",activeId).eq("dream_id",ch.dataset.share).eq("owner_id",user.id);const {error}=await q;if(error){ch.checked=!ch.checked;alert("共享设置失败："+error.message)}else await loadSharedTimeline()});const dis=document.querySelector("[data-disconnect]");if(dis)dis.onclick=()=>openConfirm({title:"解除虫洞？",message:"解除后，双方将无法继续查看彼此分享的梦。已经记录在你账户中的梦不会被删除。",confirmText:"解除虫洞",tone:"danger",action:"disconnect-wormhole",payload:{wormholeId:dis.dataset.disconnect}})}
  document.querySelector("#closeAccountBtn").onclick=()=>dialog.close();
  if(!configured)return;
  client=window.supabase.createClient(cfg.url,cfg.publishableKey);window.dreamcatcherSupabase=client;
  show("#authNotConfigured",false);show("#authForms",true);
  client.auth.onAuthStateChange(()=>setTimeout(refresh,0)); refresh();
  window.addEventListener("dreamcatcher:datachanged",()=>{if(!user||syncing)return;clearTimeout(syncTimer);syncTimer=setTimeout(syncNow,500)});
  document.querySelector("#signUpBtn").onclick=async()=>{msg("正在创建账户…");const email=authEmail.value.trim(),password=authPassword.value;const {data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)return msg(error.message,true);msg(data.session?"注册成功，正在同步…":"注册成功，请查看邮箱完成验证。")};
  document.querySelector("#signInBtn").onclick=async()=>{msg("正在登录…");const {error}=await client.auth.signInWithPassword({email:authEmail.value.trim(),password:authPassword.value});msg(error?error.message:"登录成功，正在同步…",!!error)};
  document.querySelector("#signOutBtn").onclick=async()=>{await client.auth.signOut();msg("")};
})();